In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
meteo_19 = pd.read_csv("Input/Roma-2019-Dicembre.csv", sep=";")

In [6]:
meteo_19.head()

,LOCALITA,DATA,TMEDIA °C,TMIN °C,TMAX °C,PUNTORUGIADA °C,UMIDITA %,VISIBILITA km,VENTOMEDIA km/h,VENTOMAX km/h,RAFFICA km/h,PRESSIONESLM mb,PRESSIONEMEDIA mb,PIOGGIA mm,FENOMENI
0,Roma,1/12/2019,13,7,17,8,72,20,14,24,0,1019,0,0,NaN
1,Roma,2/12/2019,15,14,17,11,76,19,22,30,0,1015,0,0,pioggia
2,Roma,3/12/2019,12,8,14,10,88,15,12,22,0,1016,0,0,nebbia
3,Roma,4/12/2019,9,4,14,3,62,20,14,26,0,1017,0,0,NaN
4,Roma,5/12/2019,9,6,14,3,65,21,8,15,0,1021,0,0,NaN

In [8]:
meteo_19.info() #E' fondamentale per la ricerca dei NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   LOCALITA           31 non-null     object
 1   DATA               31 non-null     object
 2   TMEDIA °C          31 non-null     int64
 3   TMIN °C            31 non-null     int64
 4   TMAX °C            31 non-null     int64
 5   PUNTORUGIADA °C    31 non-null     int64
 6   UMIDITA %          31 non-null     int64
 7   VISIBILITA km      31 non-null     int64
 8   VENTOMEDIA km/h    31 non-null     int64
 9   VENTOMAX km/h      31 non-null     int64
 10  RAFFICA km/h       31 non-null     int64
 11  PRESSIONESLM mb    31 non-null     int64
 12  PRESSIONEMEDIA mb  31 non-null     int64
 13  PIOGGIA mm         31 non-null     int64
 14  FENOMENI           11 non-null     object
dtypes: int64(12), object(3)
memory usage: 3.8+ KB

In [9]:
meteo_19.isna()

,LOCALITA,DATA,TMEDIA °C,TMIN °C,TMAX °C,PUNTORUGIADA °C,UMIDITA %,VISIBILITA km,VENTOMEDIA km/h,VENTOMAX km/h,RAFFICA km/h,PRESSIONESLM mb,PRESSIONEMEDIA mb,PIOGGIA mm,FENOMENI
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [10]:
meteo_19.isna().sum() #E' fondamentale per la ricerca dei NaN

LOCALITA              0
DATA                  0
TMEDIA °C             0
TMIN °C               0
TMAX °C               0
PUNTORUGIADA °C       0
UMIDITA %             0
VISIBILITA km         0
VENTOMEDIA km/h       0
VENTOMAX km/h         0
RAFFICA km/h          0
PRESSIONESLM mb       0
PRESSIONEMEDIA mb     0
PIOGGIA mm            0
FENOMENI             20
dtype: int64